spring.application.name=Hustle Economy API
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://postgres:5432/hustle}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true

app.uploads.dir=${UPLOADS_DIR:/app/uploads}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
