spring.application.name=Hustle Economy API
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://postgres:5432/hustle}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true

r2.endpoint=https://226bbe940e4062a98f643cd74fe1490b.r2.cloudflarestorage.com
r2.bucket=${R2_BUCKET:hustle}
r2.access-key=${R2_ACCESS_KEY:}
r2.secret-key=${R2_SECRET_KEY:}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.error.include-message=always
